# ---------
# CONSTANTS
# ---------

# PyGame settings
FULLSCREEN = False
WINDOW_SIZE = (960, 540)
HIDE_MOUSE = True

GAME_FPS = 60


# Colors
BLUE = (0, 0, 255)
LIGHT_BLUE = (164,219,232)
DARK_BLUE = (0,20,64)
BG_COLOR = (0, 0, 0)

# Trail settings
MAX_LEN_TRAIL = 40
TRAIL_CIRCLE_WIDTH = 10
TRAIL_COLOR_SCHEME = (DARK_BLUE, BLUE, LIGHT_BLUE)